spring.application.name=learn-chinese-backend
server.port=8080

# --- Profile Configuration ---
# Mặc định dùng 'dev' nếu không có biến APP_PROFILE
spring.profiles.active=${APP_PROFILE:dev}

# --- Gemini API (Chung cho cả Dev và Prod) ---
gemini.api.key=${GEMINI_API_KEY:fff}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
