# --- PROD ENVIRONMENT (PostgreSQL with H2 Fallback) ---

# Logic:
# 1. Ưu tiên dùng biến môi trường DB_... (Postgres)
# 2. Nếu biến môi trường KHÔNG TỒN TẠI, tự động dùng giá trị sau dấu hai chấm (H2)
logging.level.org.springframework.core.env=DEBUG

spring.datasource.url=${DB_URL1:jdbc:h2:file:./data/learnchinesedb_prod;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
spring.datasource.username=${DB_USERNAME1:sa}
spring.datasource.password=${DB_PASSWORD1:}
spring.datasource.driver-class-name=${DB_DRIVER1:org.h2.Driver}

# JPA Dialect cũng cần fallback
# Nếu là Postgres: org.hibernate.dialect.PostgreSQLDialect
# Nếu là H2: org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=${DB_PLATFORM1:org.hibernate.dialect.H2Dialect}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false